# Generated by Django 4.1.7 on 2024-01-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('nome_titular', models.CharField(max_length=255)),
                ('data_validade', models.DateField()),
                ('codigo_seguranca', models.CharField(max_length=4)),
                ('tipo', models.CharField(choices=[('credito', 'credito'), ('debito', 'debito'), ('credito_debito', 'credito_debito')], max_length=16)),
                ('excluido', models.BooleanField(default=False)),
            ],
        ),
    ]
