# Generated by Django 4.1.7 on 2024-01-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoes',
            name='codigo_seguranca',
        ),
        migrations.RemoveField(
            model_name='cartoes',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='cartoes',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='cartoes',
            name='nome_titular',
        ),
        migrations.RemoveField(
            model_name='cartoes',
            name='tipo',
        ),
    ]
