# Generated by Django 4.1.7 on 2024-01-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cartoes_codigo_seguranca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoes',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartoes',
            name='identificador_linha',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cartoes',
            name='lote',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='cartoes',
            name='nome',
            field=models.CharField(blank=True, max_length=29, null=True),
        ),
        migrations.AddField(
            model_name='cartoes',
            name='numero_lote',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cartoes',
            name='qtd_registro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartoes',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
