# Generated by Django 4.1.7 on 2024-01-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cartoes_data_cartoes_identificador_linha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoes',
            name='lote',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
