# Generated by Django 4.1.7 on 2024-01-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cartoes_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoes',
            name='identificador_linha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
